### ISSUE TITLE
CRA 3.0

### ISSUE THREAD

**Issue by longfellowone** [DemianD/create-react-app-tailwindcss#10]
Is this using the latest version of CRA 3.0?

**Comment by DemianD** [comment]
Hi @longfellowone 

This is not yet using the latest version of CRA 3.0

I'm planning to update this package soon.

**Comment by longfellowone** [comment]
Awesome, thanks for project!

**Comment by DemianD** [comment]
I’ll reopen this to keep track of this issue

**Comment by DemianD** [comment]
Hi @longfellowone, I've updated the repository to support the latest version of CRA (v3.2.0) and the latest of Tailwind CSS.

**How to update:**

1. Change the version tag in your package.json:
```
    "react-scripts-tailwindcss": "3.2.0-rc.1"
```

2. Run `npm install` or `yarn install`
