### ISSUE TITLE
Request to update tailwind to 1.x

### ISSUE THREAD

**Issue by icaroscherma** [DemianD/create-react-app-tailwindcss#12]
It is not a bug but it would be nice to have the packages in the latest version, specially because of the color naming changes and the `grey / gray`.

After manually trying to `npm install tailwindcss@^1.0 --save-dev`, the app doesn't run anymore.

**Comment by DemianD** [comment]
Hi @icaroscherma 

I'll probably update this package in a few weeks with the latest CRA and TailwindCSS version.

**Comment by icaroscherma** [comment]
Thank you for the feedback @DemianD  =) I will be watching the repo.

**Comment by DemianD** [comment]
Hi @icaroscherma, I've updated the repository to support the latest version of CRA (v3.2.0) and the latest of Tailwind CSS.

**How to update:**

1. Change the version tag in your package.json:
```
    "react-scripts-tailwindcss": "3.2.0-rc.1"
```

2. Run `npm install` or `yarn install`
